/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IconHeroicons:arrowRight': typeof import('~icons/heroicons/arrow-right')['default']
    'IconHeroicons:bars3BottomRight': typeof import('~icons/heroicons/bars3-bottom-right')['default']
    'IconHeroicons:bellAlert': typeof import('~icons/heroicons/bell-alert')['default']
    'IconHeroicons:chatBubbleLeftEllipsis': typeof import('~icons/heroicons/chat-bubble-left-ellipsis')['default']
    'IconHeroicons:check': typeof import('~icons/heroicons/check')['default']
    'IconHeroicons:eye': typeof import('~icons/heroicons/eye')['default']
    'IconHeroicons:eyeSlash': typeof import('~icons/heroicons/eye-slash')['default']
    'IconHeroicons:heart': typeof import('~icons/heroicons/heart')['default']
    'IconHeroicons:heartSolid': typeof import('~icons/heroicons/heart-solid')['default']
    'IconHeroicons:lockClosed': typeof import('~icons/heroicons/lock-closed')['default']
    'IconHeroicons:lockOpen': typeof import('~icons/heroicons/lock-open')['default']
    'IconHeroicons:pencil': typeof import('~icons/heroicons/pencil')['default']
    'IconHeroicons:sparklesSolid': typeof import('~icons/heroicons/sparkles-solid')['default']
    'IconHeroicons:starSolid': typeof import('~icons/heroicons/star-solid')['default']
    'IconHeroicons:trash': typeof import('~icons/heroicons/trash')['default']
    'IconHeroicons:xMark': typeof import('~icons/heroicons/x-mark')['default']
    IconHeroiconsStarSolid: typeof import('~icons/heroicons/star-solid')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
